# Generated by Django 4.2.1 on 2024-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_contact_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("Lead", "Lead"),
                    ("Prospect", "Prospect"),
                    ("Customer", "Customer"),
                ],
                default="Lead",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
