# Generated by Django 5.0.6 on 2024-07-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
    ]
