# Generated by Django 5.0.6 on 2024-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('meeting', 'Meeting'), ('opportunity', 'Opportunity'), ('qualified', 'Qualified'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('closed', 'Closed')], default='lead', max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
