# Generated by Django 4.2.1 on 2023-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuth',
            fields=[
                ('is_google_auth', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GoogleAuth',
                'verbose_name_plural': 'GoogleAuth',
                'db_table': 'google_auth',            
            },
        ),
    ]