# Generated by Django 5.0.6 on 2024-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_attachments_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_marketing_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_sales_access',
            field=models.BooleanField(default=False),
        ),
    ]
