# Generated by Django 5.0.6 on 2024-06-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_user_has_marketing_access_user_has_sales_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_marketing_access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_sales_access',
        ),
    ]
