# Generated by Django 5.0.6 on 2024-06-19 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_remove_user_has_marketing_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleauth',
            options={'ordering': ('-created_at',), 'verbose_name': 'GoogleAuth', 'verbose_name_plural': 'GoogleAuth'},
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='updated_by_id',
        ),
        migrations.AddField(
            model_name='googleauth',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='googleauth',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
