# Generated by Django 5.0.6 on 2024-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_user_first_name_alter_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_sales_representative_access',
            field=models.BooleanField(default=False),
        ),
    ]
