# Generated by Django 5.0.6 on 2024-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_profile_has_sales_representative_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
