# Generated by Django 5.0.7 on 2024-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('medior', 'Medior'), ('senior', 'Senior')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='workload',
            field=models.IntegerField(default=0),
        ),
    ]
