# Generated by Django 5.0.7 on 2024-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_profile_expertise_profile_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('medior', 'Medior'), ('senior', 'Senior'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
    ]
