# Generated by Django 5.0.7 on 2024-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
