FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG PIP_EXTRA_INDEX_URL

WORKDIR /appbuild

# Intall dependencies
COPY requirements.txt /appbuild

RUN apt update
## dos2unix package added 
RUN apt install -y git ruby-dev ruby-ffi postgresql-client redis-server wkhtmltopdf dos2unix 
RUN apt clean
RUN gem install sass
RUN gem install compass
# install nvm/npm
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN apt install nodejs npm -y
RUN npm -g install less
RUN apt install -y python3-pip
RUN python3 -m pip install --no-cache-dir -r requirements.txt
RUN python3 -m pip install --no-cache-dir redis

# COPY . /app
COPY docker/entrypoint.sh /appbuild
COPY docker/wait-for-postgres.sh /appbuild

# Following commands updated to fix missing entrypoint.sh build error
RUN chmod +x /appbuild/entrypoint.sh
RUN dos2unix /appbuild/entrypoint.sh

RUN chmod +x /appbuild/wait-for-postgres.sh
RUN dos2unix /appbuild/wait-for-postgres.sh

ENTRYPOINT ["./entrypoint.sh"]