# Generated by Django 5.0.6 on 2024-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
